Generate the most compact JSON representation in various places.
fafhrd91/aiohttp pull request #2877
Opened 2018-03-25 16:21 UTC by socketpair

## What do these changes do?

## Are there changes in behavior for the user?

## Related issue number

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

2018-03-25 16:25 UTC, socketpair commented on tests/test_multipart.py
> +    assert '{"привет":"мир"}'.encode('utf-8') in buf
Don't know how to remake tests without dependency on JSON dumps settings.

2018-03-25 16:35 UTC, socketpair commented on aiohttp/helpers.py
> +    return json.dumps(obj, ensure_ascii=False, allow_nan=False, separators=(',', ':'))
```
asd='превед я русский текст, как же фигово китайцам с юникодом. да уж, вот же шь у них проблемы то!!'
timeit json.dumps(asd, ensure_ascii=True)  # before patch
100000 loops, best of 3: 3.06 µs per loop

timeit json.dumps(asd, ensure_ascii=False)   # after patch
100000 loops, best of 3: 4.8 µs per loop
```

BUT

```
len(json.dumps(asd, ensure_ascii=True))  # before patch
457

len(json.dumps(asd, ensure_ascii=False))  # after patch
97
```

```

2018-03-25 16:38 UTC, socketpair commented on aiohttp/helpers.py
> +    return json.dumps(obj, ensure_ascii=False, allow_nan=False, separators=(',', ':'))
So, this is VOLUME vs CPU trade-off. Don't know what to do next -- maybe some way to configure it globally ?

2018-03-26 02:48 UTC, asvetlov commented
I think it's ok to apply `ensure_ascii`: JSON is utf-8 encoded data.
But `allow_nan` and custom separators modify output too much. Please use a custom serializer in your project to change these arguments.

2018-04-01 06:50 UTC, asvetlov requested changes
See comment above

2018-04-01 12:03 UTC, kxepal commented
Disallowing NaN is actually good since NaNs aren't in JSON specification - that's rudiment from the dark days. But `ensure_ascii=False` may lead to breaking compatibility case with some json libraries which don't expect utf-8 characters and strictly follows json.org specification.

2018-04-01 13:39 UTC, samuelcolvin commented
Surely no JSON library will be broken by a change to separators. How can this be a problem?

2018-04-01 16:46 UTC, hellysmile commented
Hello there! What about small idea, to make it configurable per application? It can be really useful! I often see rapidjson/ujson/etc in projects and it makes annoying always pass dumps=...

2018-04-01 17:48 UTC, kxepal commented
@hellysmile 
Hi! Eventually, it's already configurable. Just create your own JsonEncoder instance with proper setup and pass it around via dump argument.

2018-05-07 08:47 UTC, asvetlov commented
I suggest closing the issue.
If somebody wants to get a compact JSON dump he can use a custom JSON serializer.

2018-05-13 20:47 UTC, socketpair commented
@asvetlov

2018-05-13 20:47 UTC, closed without merging

2024-06-23 11:05 UTC, socketpair commented
`json_response.__kwdefaults__['dumps'] = partial(json.dumps, ensure_ascii=False)` for those who find this issue.