Fix multiple calls to runner shutdown with multiple sites
fafhrd91/aiohttp pull request #4646
Opened 2020-03-18 16:19 UTC by achimnol

## What do these changes do?

Runner shutdown invocation from BaseSite to BaseRunner to avoid multiple (duplicate)
shutdown calls when there are multiple sites registered to a single runner and application.

Currently startup handlers of application runners are called only once regardless of the number
of registered sites, but the shutdown handlers are called multiple times.

## Are there changes in behavior for the user?

I'd expect this will require an API change: `shutdown_timeout` should be moved to runners
from sites.

But I need discussion/confirmation from the core developers since I'm not quite sure about
the relationship between runners, servers, and application in the `web_runner.py` module.

Therefore, this PR is first created as draft until I get proper understanding and we agree with the
final API changes if required.

## Related issue number

I have mentioned this issue in the gitter chat.

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

2020-04-04 07:03 UTC, achimnol commented
The CI failure of the final commit seems to be a timeout issue in the CI server. (The failed test has nothing to do with this PR)

2020-10-16 09:47 UTC, asvetlov reviewed
The multiple shutdowns were the initial intention.
Technically, if you start the application on multiple sites -- you can shut them down independently.

I think I understand your wish to shutdown everything on the application closing. This desire makes sense but it should be implemented as a different signal (the name is the subject for discussion).

Please feel free to prepare a PR for this not-existing-yet signal support.

2020-10-16 09:49 UTC, asvetlov requested changes
Sorry, I cannot accept the PR as-is, see the comment above.

2020-10-19 01:36 UTC, achimnol commented
Okay, I understand that the intention was to run shutdown handlers per site for a single app.
Then, shouldn't do the framework run the startup handlers per site in the same way?
If so, since currently the app is unaware of site (as it's an abstraction), we may need to expose the site to the app codes to distinguish its running context.
The main purpose of this PR was to *clarify and make it consistent* on how many times startup/shutdown handlers are called in what context.

2020-10-21 07:31 UTC, asvetlov commented
In my mind current signals are:
startup [app]
cleanup_ctx [app]
shundown [site]
cleanup [app]

app signals are called once per application, site signal is called for every site.
I agree that the list of existing signals is not complete and can be extended.
Not sure that we need the full possible matrix but I'm okay to add new signals if somebody needs them.

2020-10-23 17:09 UTC, achimnol commented
Hm.. If I understand your description & intentions correctly, do the followings match with your thoughts?

 * startup: initialize/allocate the underlying resources such as DB connection pools => per-app
 * shutdown: cancel ongoing request handlers and tasks when interrupted => per-site (because request-response connections are tied with site-specific transports)
 * cleanup: release/destroy the underlying resources such as DB connection pools => per-app

If so, I think [the docs](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.Application.on_shutdown) should be clarified that "shutdown" is executed per site, with possibility of multiple executions if there are multiple sites running the same app instance.

If you are okay, I'll rewrite this PR to update the docs, instead of patching the current behavior, though I need to refactor my codes to conform with it...

2020-10-23 17:21 UTC, achimnol commented
Also, as the doc suggests: "We suggest keeping a list of long running handlers in Application dictionary."

For multi-site apps, we should be able to distinguish which long-running handlers belong to which site, because the shutdown handlers will be called multiple times but we have no contextual information about which site that current signal invocation is for.

To this end, the following enhancements are alos required in the code-level:
* Add a reference to the site to the `BaseRequest` object so that long-running handlers can keep the reference to themselves in the app's per-site `WeakSet`.
* Pass the site object to the shutdown signal handlers so that they can know the context.
* Update [the graceful shutdown example in the docs](https://docs.aiohttp.org/en/stable/web_advanced.html#aiohttp-web-graceful-shutdown) to reflect above changes, e.g., using the site object passed to the shutdown signal handler to distinguish the set of long-running handlers to cancel.

2020-11-16 10:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aio-libs/aiohttp?pullRequest=4646) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aio-libs/aiohttp?pullRequest=4646) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aio-libs/aiohttp?pullRequest=4646) it.</sub>

2020-11-20 10:51 UTC, asvetlov commented
> Add a reference to the site to the BaseRequest object so that long-running handlers can keep the reference to themselves in the app's per-site handler set.
Ok

> Pass the site object to the shutdown signal handlers so that they can know the context.
Sorry, it is a breaking change. We cannot mutate the signal handler signature.
But we can add a new signal for the *fixed* shutdown and deprecate the existing one.

> Update the graceful shutdown example in the docs to reflect above changes, e.g., using the site object passed to the shutdown signal handler to distinguish the set of long-running handlers to cancel.
Ok

If you want to do this task -- you are welcome!

2024-01-29 01:53 UTC, webknjaz commented
@achimnol are you planning to resume working on this?

2024-01-29 02:02 UTC, Dreamsorcerer commented
I think I also fixed this in #7780, so I'll close this. Reopen if you think there's still something of value here.

> For multi-site apps, we should be able to distinguish which long-running handlers belong to which site, because the shutdown handlers will be called multiple times but we have no contextual information about which site that current signal invocation is for.

I think this is still relevant and something I also noticed during that work.

2024-01-29 02:02 UTC, closed without merging