GunicornWebWorker subclasses can config AppRunner
fafhrd91/aiohttp pull request #4720
Opened 2020-04-27 21:04 UTC by bmbouter

Currently there is no way to configure the Application Runner created by
the `aiohttp.GunicornWebWorker`.

This allows `GunicornWebWorker` subclasses to configure its
`ApplicationRunner` by introducing the
`GunicornWebWorker._get_application_runner_instance` method.

## What do these changes do?

This implements Design 1 from this request for comment, comment https://github.com/aio-libs/aiohttp/issues/2988#issuecomment-611124997

## Are there changes in behavior for the user?

No

## Related issue number

https://github.com/aio-libs/aiohttp/issues/2988

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names. 
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

2020-11-16 10:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aio-libs/aiohttp?pullRequest=4720) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aio-libs/aiohttp?pullRequest=4720) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aio-libs/aiohttp?pullRequest=4720) it.</sub>

2020-11-23 14:49 UTC, asvetlov requested changes
The PR doesn't pass the linter CI checks.
Sorry, I cannot accept it as-is.

2020-11-23 14:49 UTC, asvetlov commented on aiohttp/worker.py
> +    def _get_application_runner_instance(self, app, **kwargs):
The method should be documented and type hinted.

2020-11-23 14:49 UTC, asvetlov commented on aiohttp/worker.py
> +    def _get_application_runner_instance(self, app, **kwargs):
How `**kwargs` are used? I see it is always an empty dict.

2022-04-28 19:00 UTC, bmbouter commented
Our project uses a locally patched workaround. I'd still like to see this accepted so we don't have to carry it, but I'm unable to finish it so I'll close for now.

2022-04-28 19:00 UTC, closed without merging