Issue 5156
fafhrd91/aiohttp pull request #5176
Opened 2020-10-29 14:08 UTC by derlih

## What do these changes do?

Workaround for incorrect socket.getaddrinfo return value in rare case

## Are there changes in behavior for the user?

No

## Related issue number

#5156 

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [x] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` for example (588.bugfix)
  * if you don't have an `issue_id` change it to the pr id after creating the pr
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: "Fix issue with non-ascii contents in doctest text files."

2020-10-29 16:04 UTC, asvetlov reviewed
I like this PR
@danielnelson could you please check the pull request and make sure that the problem disappeared?

2020-10-29 16:45 UTC, derlih commented
@asvetlov the code cov check failed because #4556 was merged without coverage of the line
```python
if family == socket.AF_INET6 and address[3]:  # type: ignore
```
I can add a unit test for this branch as well to bypass the coverage check, but I don't understand how the mock data should look like.

Also in https://docs.aiohttp.org/en/latest/contributing.html is mentioned about `make cov` but there is no `cov` target in Makefile.
```console
$ make cov
make: *** No rule to make target 'cov'.  Stop.
```

2020-10-29 18:01 UTC, danielnelson commented
```
$ cat bug.py
import asyncio
import aiohttp


async def main():
    async with aiohttp.ClientSession() as session:
        async with session.get('http://python.org') as response:
            print(response.status)


asyncio.run(main())
```
```
$ python bug.py 
Bad address format in (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', (10, b'\x01\xbb\x00\x00\x00\x00*\x04NB\x00-\x00\x00'))
200
Future exception was never retrieved
future: <Future finished exception=SSLError(1, '[SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2691)')>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 530, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/usr/lib/python3.7/ssl.py", line 778, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2691)
```

Not sure what that SSLError is about, possibly I did something incorrect when compiling?

I suspect that this patch would be very noisy to run, as every remote with an IPv6 address would log.

2020-10-29 18:17 UTC, danielnelson commented
If I enable the AsyncResolver it also raises:
```
Traceback (most recent call last):
  File "/home/dbn/src/aiohttp/aiohttp/connector.py", line 940, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.7/asyncio/base_events.py", line 962, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.7/asyncio/base_events.py", line 928, in create_connection
    sock = socket.socket(family=family, type=type, proto=proto)
  File "/usr/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 97] Address family not supported by protocol

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bug.py", line 13, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "bug.py", line 9, in main
    async with session.get(sys.argv[1]) as response:
  File "/home/dbn/src/aiohttp/aiohttp/client.py", line 1070, in __aenter__
    self._resp = await self._coro
  File "/home/dbn/src/aiohttp/aiohttp/client.py", line 482, in _request
    req, traces=traces, timeout=real_timeout
  File "/home/dbn/src/aiohttp/aiohttp/connector.py", line 508, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/dbn/src/aiohttp/aiohttp/connector.py", line 863, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/dbn/src/aiohttp/aiohttp/connector.py", line 1021, in _create_direct_connection
    raise last_exc
  File "/home/dbn/src/aiohttp/aiohttp/connector.py", line 1003, in _create_direct_connection
    client_error=client_error,
  File "/home/dbn/src/aiohttp/aiohttp/connector.py", line 946, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.python.org:80 ssl:default [Address family not supported by protocol]
```

2020-10-30 07:48 UTC, derlih commented
@danielnelson looks like the code passed the resolver and tries to use secured connection for http.

2020-10-30 18:48 UTC, webknjaz commented on aiohttp/resolver.py
> +            if family == socket.AF_INET6 and len(address) != 4:
I think this heuristic is weak. It's better to set a proper flag for the `getaddrinfo()` call.

2020-10-30 19:06 UTC, webknjaz requested changes
I'm pretty sure that the correct solution should be setting the `AI_ADDRCONFIG` flag: https://github.com/aio-libs/aiohttp/issues/5156#issuecomment-719740995.

2020-10-31 09:30 UTC, derlih commented
@webknjaz 
Do you think if it makes sense to add `socket.AI_ADDRCONFIG` to `"flags"` in
```python
            hosts.append(
                {
                    "hostname": hostname,
                    "host": host,
                    "port": port,
                    "family": family,
                    "proto": proto,
                    "flags": socket.AI_NUMERICHOST | socket.AI_NUMERICSERV,
                }
            )
```
?

2020-10-31 10:38 UTC, webknjaz commented
@derlih no, that thing is copied from `socket.getnameinfo()` which works on already filtered out entries.

2020-10-31 10:42 UTC, webknjaz commented on CHANGES/5156.bugfix
> +Workaround wrong return value of socket.getaddrinfo in rare case
Fixed querying the address families from DNS that the current host supports.

2020-10-31 10:44 UTC, webknjaz commented
@danielnelson please verify that this fix works for you.

2020-10-31 20:38 UTC, danielnelson commented
Yes, this patch is working great!

If anyone needs to reproduce, I needed to update my test script to read the response in order to avoid the `ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2691)` error.  I think this was related to #3535.
```python
import asyncio
import aiohttp
import sys


async def main():
    async with aiohttp.ClientSession() as session:
        async with session.get(sys.argv[1]) as response:
            print(response.status)
            await response.read()


asyncio.run(main())
```

```
$ python bug.py http://python.org
200
```

Of course, this change does not resolve the issue if using the AsyncResolver.  Would it make sense for me to open a new issue for this?

2020-11-01 09:30 UTC, asvetlov commented
Ok, let's apply the patch.
KRB5_S_INIT warning will be solved in aiohttp 4.0 I believe, #5102 is a blocker for this feature currently.
Agree, AsyncResolver is a different beast and should be addressed separately.

Thank you all, and especially @derlih for the patch (and patience in the patch implementation changing).

@webknjaz do you want to approve it?

2020-11-01 09:37 UTC, webknjaz approved these changes

2020-11-01 09:40 UTC, merged