replace blockdiag with graphviz in docs
fafhrd91/aiohttp pull request #9359
Opened 2024-09-30 18:09 UTC by Cycloctane

## What do these changes do?

- replace blockdiag with graphviz in docs/tracing_reference.rst
- remove `sphinxcontrib-blockdiag` dependency in requirements

## Are there changes in behavior for the user?

## Is it a substantial burden for the maintainers to support this?

## Related issue number

Fixes #9134 

## Checklist

- [x] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is &lt;Name&gt; &lt;Surname&gt;.
  * Please keep alphabetical order, the file is sorted by names.
- [ ] Add a new news fragment into the `CHANGES/` folder
  * name it `<issue_or_pr_num>.<type>.rst` (e.g. `588.bugfix.rst`)
  * if you don't have an issue number, change it to the pull request
    number after creating the PR
    * `.bugfix`: A bug fix for something the maintainers deemed an
      improper undesired behavior that got corrected to match
      pre-agreed expectations.
    * `.feature`: A new behavior, public APIs. That sort of stuff.
    * `.deprecation`: A declaration of future API removals and breaking
      changes in behavior.
    * `.breaking`: When something public is removed in a breaking way.
      Could be deprecated in an earlier release.
    * `.doc`: Notable updates to the documentation structure or build
      process.
    * `.packaging`: Notes for downstreams about unobvious side effects
      and tooling. Changes in the test invocation considerations and
      runtime assumptions.
    * `.contrib`: Stuff that affects the contributor experience. e.g.
      Running tests, building the docs, setting up the development
      environment.
    * `.misc`: Changes that are hard to assign to any of the above
      categories.
  * Make sure to use full sentences with correct case and punctuation,
    for example:
    ```rst
    Fixed issue with non-ascii contents in doctest text files
    -- by :user:`contributor-gh-handle`.
    ```

    Use the past tense or the present tense a non-imperative mood,
    referring to what's changed compared to the last released version
    of this project.

2024-09-30 18:36 UTC, Cycloctane commented
Note that GraphViz requires [additonal packages](https://graphviz.org/download/) to be installed to render diagrams when building documentation. This change haven't been presented yet.

2024-09-30 20:49 UTC, Dreamsorcerer commented on docs/conf.py
> +    "sphinx.ext.graphviz",
Let's keep it alphabetical.
```suggestion
    "sphinx.ext.graphviz",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
```

2024-09-30 20:51 UTC, Dreamsorcerer commented on requirements/broken-projects.in
Let's delete the file and references to it.

2024-09-30 20:56 UTC, Dreamsorcerer requested changes
If you follow the link from the RTD job in the PR (https://aiohttp--9359.org.readthedocs.build/en/9359/tracing_reference.html) you can preview the docs. Currently, there are no diagrams rendered.

2024-09-30 20:58 UTC, Dreamsorcerer commented
> If you follow the link from the RTD job in the PR (https://aiohttp--9359.org.readthedocs.build/en/9359/tracing_reference.html) you can preview the docs. Currently, there are no diagrams rendered.

I'm guessing that might because of your comment about needing another package, though I'm a little surprised the build doesn't fail if a dependency is missing...

2024-09-30 20:58 UTC, Dreamsorcerer commented on CHANGES/9359.contrib.rst
> +Changed diagram images generator from blockdiag to GraphViz.
```suggestion
Changed diagram images generator from ``blockdiag`` to GraphViz.
```

2024-10-01 13:06 UTC, Dreamsorcerer commented
I think that works well enough. Thanks for that.

2024-10-01 13:06 UTC, merged

2024-10-01 13:06 UTC, Dreamsorcerer commented
Could you handle the backport as well?